package com.toutiao.pojo;

public class NewsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.id
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.tag
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.abstract_value
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    private String abstractValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.title
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.imageUrl
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    private String imageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.label
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.sourceUrl
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    private String sourceurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.littleImageUrl
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    private String littleimageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.time
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.next_max_behot_time
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    private String nextMaxBehotTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.id
     *
     * @return the value of news_info.id
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.id
     *
     * @param id the value for news_info.id
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.tag
     *
     * @return the value of news_info.tag
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.tag
     *
     * @param tag the value for news_info.tag
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.abstract_value
     *
     * @return the value of news_info.abstract_value
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public String getAbstractValue() {
        return abstractValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.abstract_value
     *
     * @param abstractValue the value for news_info.abstract_value
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void setAbstractValue(String abstractValue) {
        this.abstractValue = abstractValue == null ? null : abstractValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.title
     *
     * @return the value of news_info.title
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.title
     *
     * @param title the value for news_info.title
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.imageUrl
     *
     * @return the value of news_info.imageUrl
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.imageUrl
     *
     * @param imageurl the value for news_info.imageUrl
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.label
     *
     * @return the value of news_info.label
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.label
     *
     * @param label the value for news_info.label
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.sourceUrl
     *
     * @return the value of news_info.sourceUrl
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public String getSourceurl() {
        return sourceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.sourceUrl
     *
     * @param sourceurl the value for news_info.sourceUrl
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void setSourceurl(String sourceurl) {
        this.sourceurl = sourceurl == null ? null : sourceurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.littleImageUrl
     *
     * @return the value of news_info.littleImageUrl
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public String getLittleimageurl() {
        return littleimageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.littleImageUrl
     *
     * @param littleimageurl the value for news_info.littleImageUrl
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void setLittleimageurl(String littleimageurl) {
        this.littleimageurl = littleimageurl == null ? null : littleimageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.time
     *
     * @return the value of news_info.time
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.time
     *
     * @param time the value for news_info.time
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.next_max_behot_time
     *
     * @return the value of news_info.next_max_behot_time
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public String getNextMaxBehotTime() {
        return nextMaxBehotTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.next_max_behot_time
     *
     * @param nextMaxBehotTime the value for news_info.next_max_behot_time
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void setNextMaxBehotTime(String nextMaxBehotTime) {
        this.nextMaxBehotTime = nextMaxBehotTime == null ? null : nextMaxBehotTime.trim();
    }

	@Override
	public String toString() {
		return "NewsInfo [id=" + id + ", tag=" + tag + ", abstractValue=" + abstractValue + ", title=" + title
				+ ", imageurl=" + imageurl + ", label=" + label + ", sourceurl=" + sourceurl + ", littleimageurl="
				+ littleimageurl + ", time=" + time + ", nextMaxBehotTime=" + nextMaxBehotTime + "]";
	}
    
    
}