package com.toutiao.pojo;

import java.util.ArrayList;
import java.util.List;

public class NewsInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public NewsInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTagIsNull() {
            addCriterion("tag is null");
            return (Criteria) this;
        }

        public Criteria andTagIsNotNull() {
            addCriterion("tag is not null");
            return (Criteria) this;
        }

        public Criteria andTagEqualTo(String value) {
            addCriterion("tag =", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotEqualTo(String value) {
            addCriterion("tag <>", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThan(String value) {
            addCriterion("tag >", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThanOrEqualTo(String value) {
            addCriterion("tag >=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThan(String value) {
            addCriterion("tag <", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThanOrEqualTo(String value) {
            addCriterion("tag <=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLike(String value) {
            addCriterion("tag like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotLike(String value) {
            addCriterion("tag not like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagIn(List<String> values) {
            addCriterion("tag in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotIn(List<String> values) {
            addCriterion("tag not in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagBetween(String value1, String value2) {
            addCriterion("tag between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotBetween(String value1, String value2) {
            addCriterion("tag not between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andAbstractValueIsNull() {
            addCriterion("abstract_value is null");
            return (Criteria) this;
        }

        public Criteria andAbstractValueIsNotNull() {
            addCriterion("abstract_value is not null");
            return (Criteria) this;
        }

        public Criteria andAbstractValueEqualTo(String value) {
            addCriterion("abstract_value =", value, "abstractValue");
            return (Criteria) this;
        }

        public Criteria andAbstractValueNotEqualTo(String value) {
            addCriterion("abstract_value <>", value, "abstractValue");
            return (Criteria) this;
        }

        public Criteria andAbstractValueGreaterThan(String value) {
            addCriterion("abstract_value >", value, "abstractValue");
            return (Criteria) this;
        }

        public Criteria andAbstractValueGreaterThanOrEqualTo(String value) {
            addCriterion("abstract_value >=", value, "abstractValue");
            return (Criteria) this;
        }

        public Criteria andAbstractValueLessThan(String value) {
            addCriterion("abstract_value <", value, "abstractValue");
            return (Criteria) this;
        }

        public Criteria andAbstractValueLessThanOrEqualTo(String value) {
            addCriterion("abstract_value <=", value, "abstractValue");
            return (Criteria) this;
        }

        public Criteria andAbstractValueLike(String value) {
            addCriterion("abstract_value like", value, "abstractValue");
            return (Criteria) this;
        }

        public Criteria andAbstractValueNotLike(String value) {
            addCriterion("abstract_value not like", value, "abstractValue");
            return (Criteria) this;
        }

        public Criteria andAbstractValueIn(List<String> values) {
            addCriterion("abstract_value in", values, "abstractValue");
            return (Criteria) this;
        }

        public Criteria andAbstractValueNotIn(List<String> values) {
            addCriterion("abstract_value not in", values, "abstractValue");
            return (Criteria) this;
        }

        public Criteria andAbstractValueBetween(String value1, String value2) {
            addCriterion("abstract_value between", value1, value2, "abstractValue");
            return (Criteria) this;
        }

        public Criteria andAbstractValueNotBetween(String value1, String value2) {
            addCriterion("abstract_value not between", value1, value2, "abstractValue");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andImageurlIsNull() {
            addCriterion("imageUrl is null");
            return (Criteria) this;
        }

        public Criteria andImageurlIsNotNull() {
            addCriterion("imageUrl is not null");
            return (Criteria) this;
        }

        public Criteria andImageurlEqualTo(String value) {
            addCriterion("imageUrl =", value, "imageurl");
            return (Criteria) this;
        }

        public Criteria andImageurlNotEqualTo(String value) {
            addCriterion("imageUrl <>", value, "imageurl");
            return (Criteria) this;
        }

        public Criteria andImageurlGreaterThan(String value) {
            addCriterion("imageUrl >", value, "imageurl");
            return (Criteria) this;
        }

        public Criteria andImageurlGreaterThanOrEqualTo(String value) {
            addCriterion("imageUrl >=", value, "imageurl");
            return (Criteria) this;
        }

        public Criteria andImageurlLessThan(String value) {
            addCriterion("imageUrl <", value, "imageurl");
            return (Criteria) this;
        }

        public Criteria andImageurlLessThanOrEqualTo(String value) {
            addCriterion("imageUrl <=", value, "imageurl");
            return (Criteria) this;
        }

        public Criteria andImageurlLike(String value) {
            addCriterion("imageUrl like", value, "imageurl");
            return (Criteria) this;
        }

        public Criteria andImageurlNotLike(String value) {
            addCriterion("imageUrl not like", value, "imageurl");
            return (Criteria) this;
        }

        public Criteria andImageurlIn(List<String> values) {
            addCriterion("imageUrl in", values, "imageurl");
            return (Criteria) this;
        }

        public Criteria andImageurlNotIn(List<String> values) {
            addCriterion("imageUrl not in", values, "imageurl");
            return (Criteria) this;
        }

        public Criteria andImageurlBetween(String value1, String value2) {
            addCriterion("imageUrl between", value1, value2, "imageurl");
            return (Criteria) this;
        }

        public Criteria andImageurlNotBetween(String value1, String value2) {
            addCriterion("imageUrl not between", value1, value2, "imageurl");
            return (Criteria) this;
        }

        public Criteria andLabelIsNull() {
            addCriterion("label is null");
            return (Criteria) this;
        }

        public Criteria andLabelIsNotNull() {
            addCriterion("label is not null");
            return (Criteria) this;
        }

        public Criteria andLabelEqualTo(String value) {
            addCriterion("label =", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotEqualTo(String value) {
            addCriterion("label <>", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelGreaterThan(String value) {
            addCriterion("label >", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelGreaterThanOrEqualTo(String value) {
            addCriterion("label >=", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLessThan(String value) {
            addCriterion("label <", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLessThanOrEqualTo(String value) {
            addCriterion("label <=", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLike(String value) {
            addCriterion("label like", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotLike(String value) {
            addCriterion("label not like", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelIn(List<String> values) {
            addCriterion("label in", values, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotIn(List<String> values) {
            addCriterion("label not in", values, "label");
            return (Criteria) this;
        }

        public Criteria andLabelBetween(String value1, String value2) {
            addCriterion("label between", value1, value2, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotBetween(String value1, String value2) {
            addCriterion("label not between", value1, value2, "label");
            return (Criteria) this;
        }

        public Criteria andSourceurlIsNull() {
            addCriterion("sourceUrl is null");
            return (Criteria) this;
        }

        public Criteria andSourceurlIsNotNull() {
            addCriterion("sourceUrl is not null");
            return (Criteria) this;
        }

        public Criteria andSourceurlEqualTo(String value) {
            addCriterion("sourceUrl =", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlNotEqualTo(String value) {
            addCriterion("sourceUrl <>", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlGreaterThan(String value) {
            addCriterion("sourceUrl >", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlGreaterThanOrEqualTo(String value) {
            addCriterion("sourceUrl >=", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlLessThan(String value) {
            addCriterion("sourceUrl <", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlLessThanOrEqualTo(String value) {
            addCriterion("sourceUrl <=", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlLike(String value) {
            addCriterion("sourceUrl like", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlNotLike(String value) {
            addCriterion("sourceUrl not like", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlIn(List<String> values) {
            addCriterion("sourceUrl in", values, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlNotIn(List<String> values) {
            addCriterion("sourceUrl not in", values, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlBetween(String value1, String value2) {
            addCriterion("sourceUrl between", value1, value2, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlNotBetween(String value1, String value2) {
            addCriterion("sourceUrl not between", value1, value2, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlIsNull() {
            addCriterion("littleImageUrl is null");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlIsNotNull() {
            addCriterion("littleImageUrl is not null");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlEqualTo(String value) {
            addCriterion("littleImageUrl =", value, "littleimageurl");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlNotEqualTo(String value) {
            addCriterion("littleImageUrl <>", value, "littleimageurl");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlGreaterThan(String value) {
            addCriterion("littleImageUrl >", value, "littleimageurl");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlGreaterThanOrEqualTo(String value) {
            addCriterion("littleImageUrl >=", value, "littleimageurl");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlLessThan(String value) {
            addCriterion("littleImageUrl <", value, "littleimageurl");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlLessThanOrEqualTo(String value) {
            addCriterion("littleImageUrl <=", value, "littleimageurl");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlLike(String value) {
            addCriterion("littleImageUrl like", value, "littleimageurl");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlNotLike(String value) {
            addCriterion("littleImageUrl not like", value, "littleimageurl");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlIn(List<String> values) {
            addCriterion("littleImageUrl in", values, "littleimageurl");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlNotIn(List<String> values) {
            addCriterion("littleImageUrl not in", values, "littleimageurl");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlBetween(String value1, String value2) {
            addCriterion("littleImageUrl between", value1, value2, "littleimageurl");
            return (Criteria) this;
        }

        public Criteria andLittleimageurlNotBetween(String value1, String value2) {
            addCriterion("littleImageUrl not between", value1, value2, "littleimageurl");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(String value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(String value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(String value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(String value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(String value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(String value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLike(String value) {
            addCriterion("time like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotLike(String value) {
            addCriterion("time not like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<String> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<String> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(String value1, String value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(String value1, String value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeIsNull() {
            addCriterion("next_max_behot_time is null");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeIsNotNull() {
            addCriterion("next_max_behot_time is not null");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeEqualTo(String value) {
            addCriterion("next_max_behot_time =", value, "nextMaxBehotTime");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeNotEqualTo(String value) {
            addCriterion("next_max_behot_time <>", value, "nextMaxBehotTime");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeGreaterThan(String value) {
            addCriterion("next_max_behot_time >", value, "nextMaxBehotTime");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeGreaterThanOrEqualTo(String value) {
            addCriterion("next_max_behot_time >=", value, "nextMaxBehotTime");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeLessThan(String value) {
            addCriterion("next_max_behot_time <", value, "nextMaxBehotTime");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeLessThanOrEqualTo(String value) {
            addCriterion("next_max_behot_time <=", value, "nextMaxBehotTime");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeLike(String value) {
            addCriterion("next_max_behot_time like", value, "nextMaxBehotTime");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeNotLike(String value) {
            addCriterion("next_max_behot_time not like", value, "nextMaxBehotTime");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeIn(List<String> values) {
            addCriterion("next_max_behot_time in", values, "nextMaxBehotTime");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeNotIn(List<String> values) {
            addCriterion("next_max_behot_time not in", values, "nextMaxBehotTime");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeBetween(String value1, String value2) {
            addCriterion("next_max_behot_time between", value1, value2, "nextMaxBehotTime");
            return (Criteria) this;
        }

        public Criteria andNextMaxBehotTimeNotBetween(String value1, String value2) {
            addCriterion("next_max_behot_time not between", value1, value2, "nextMaxBehotTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Feb 26 11:37:33 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_info
     *
     * @mbggenerated Mon Feb 26 11:37:33 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}